[package]
name = "sf-protos"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.3"
prost-types = "0.12.3"
prost-wkt = "0.5.0"
prost-wkt-types = "0.5.0"
serde = "1.0.196"

[build-dependencies]
prost-build = "0.12.3"
prost-wkt-build = "0.5.0"
